# Validation Constants for Entities

# Departments
DEPT_NAME_MIN_LEN = 2
DEPT_NAME_MAX_LEN = 100
DEPT_CODE_MIN_LEN = 2
DEPT_CODE_MAX_LEN = 10
DEPT_DESC_MAX_LEN = 1000

# Employees
EMP_NAME_MIN_LEN = 2
EMP_NAME_MAX_LEN = 150
EMP_DESIGNATION_MAX_LEN = 100

# Roles
ROLE_NAME_MIN_LEN = 2
ROLE_NAME_MAX_LEN = 50
ROLE_DESC_MAX_LEN = 500
ROLE_PERMISSIONS_MAX_ITEMS = 200

# Asset Categories
CAT_NAME_MIN_LEN = 2
CAT_NAME_MAX_LEN = 100
CAT_CODE_MIN_LEN = 2
CAT_CODE_MAX_LEN = 10
CAT_DESC_MAX_LEN = 1000

# Assets
ASSET_NAME_MIN_LEN = 2
ASSET_NAME_MAX_LEN = 150
ASSET_MANUFACTURER_MAX_LEN = 100
ASSET_MODEL_MAX_LEN = 100
ASSET_IMAGE_URLS_MAX_ITEMS = 10

# Allocations
ALLOC_NOTES_MAX_LEN = 1000

# Shared Resources
RESOURCE_NAME_MIN_LEN = 2
RESOURCE_NAME_MAX_LEN = 150
RESOURCE_AMENITIES_MAX_ITEMS = 10
RESOURCE_IMAGE_URLS_MAX_ITEMS = 10
RESOURCE_DEFAULT_MIN_DURATION = 60
RESOURCE_DEFAULT_MAX_DURATION = 480
RESOURCE_DEFAULT_ADVANCE_DAYS = 30

# Bookings
BOOKING_TITLE_MIN_LEN = 2
BOOKING_TITLE_MAX_LEN = 200
BOOKING_ATTENDEES_MAX_ITEMS = 100

# Maintenance Requests
MAINT_DESC_MIN_LEN = 10
MAINT_DESC_MAX_LEN = 5000
MAINT_ATTACHMENT_URLS_MAX_ITEMS = 10
MAINT_APPROVAL_COMMENTS_MAX_LEN = 1000
MAINT_LOG_DETAILS_MAX_LEN = 2000

# Audit Cycles
AUDIT_NAME_MIN_LEN = 2
AUDIT_NAME_MAX_LEN = 150
AUDIT_REPORT_DISCREPANCY_MAX_LEN = 2000
AUDIT_REPORT_PHOTOS_MAX_ITEMS = 10

# Notifications
NOTIF_TITLE_MIN_LEN = 2
NOTIF_TITLE_MAX_LEN = 150
NOTIF_BODY_MAX_LEN = 1000

# API Settings
DEFAULT_PAGE_LIMIT = 25
MAX_PAGE_LIMIT = 100
